### ISSUE TITLE
ImportError get_best_invocation_for_this_pip

### ISSUE THREAD

**Issue by remimorvan** [remimorvan/knowledge-clustering#49]
When running knowledge init (or any command):

```
Traceback (most recent call last):
  File "/home/cm/.local/bin/knowledge", line 5, in <module>
    from knowledge_clustering.scripts.app import cli
  File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/scripts/app.py", line 22, in <module>
    from knowledge_clustering.check_update import check_update
  File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/check_update.py", line 7, in <module>
    from pip._internal.utils.entrypoints import get_best_invocation_for_this_pip
ImportError: cannot import name 'get_best_invocation_for_this_pip' from 'pip._internal.utils.entrypoints' (/usr/lib/python3/dist-packages/pip/_internal/utils/entrypoints.py)
```

**Comment by remimorvan** [comment]
[Commit d07fee6](https://github.com/remimorvan/knowledge-clustering/commit/d07fee6ee85a7858c34a7fdfc10bc54d8f1f288c) should fix this issue: I no longer use `get_best_invocation_for_this_pip` (which I suppose was a bad idea anyway).
