### ISSUE TITLE
Cluster: nltk data

### ISSUE THREAD

**Issue by remimorvan** [remimorvan/knowledge-clustering#53]
`nltk` seems to have changed the name of its packages/data dir.
Even after running `knowledge init`, the following errors are obtained.
```
cmarcille@ubuntu-laptop:~/Documents/Manuscrit/Manuscrit knowledge cluster -k Knowledge/kl-configure.tex -d main.diagnose
Traceback (most recent call last):
  File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/distance.py", line 125, in breakup_notion
    nltk.word_tokenize(kl, language="english")
  File "/home/cm/.local/lib/python3.10/site-packages/nltk/tokenize/__init__.py", line 142, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
  File "/home/cm/.local/lib/python3.10/site-packages/nltk/tokenize/__init__.py", line 119, in sent_tokenize
    tokenizer = _get_punkt_tokenizer(language)
  File "/home/cm/.local/lib/python3.10/site-packages/nltk/tokenize/__init__.py", line 105, in _get_punkt_tokenizer
    return PunktTokenizer(language)
  File "/home/cm/.local/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 1744, in __init__
    self.load_lang(lang)
  File "/home/cm/.local/lib/python3.10/site-packages/nltk/tokenize/punkt.py", line 1749, in load_lang
    lang_dir = find(f"tokenizers/punkt_tab/{lang}/")
  File "/home/cm/.local/lib/python3.10/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - '/home/cm/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cm/.local/bin/knowledge", line 8, in <module>
    sys.exit(cli())
  File "/home/cm/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/cm/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/cm/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cm/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cm/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/scripts/app.py", line 130, in cluster
    clustering.app(kl_filename, dg_filename, scope, print_kl, lang, config_filename)
  File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/clustering.py", line 38, in app
    scopes_meaning = scope_meaning.infer_all_scopes(
  File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/scope_meaning.py", line 68, in infer_all_scopes
    scopes_meaning[scope], infer_scope(bag, scope, lang, stemmer)
  File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/scope_meaning.py", line 35, in infer_scope
    list_kl_broke: list[tuple[list[str], str]] = [
  File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/scope_meaning.py", line 36, in <listcomp>
    dist.breakup_notion(kl, lang) for kl in list_kl
  File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/distance.py", line 133, in breakup_notion
    raise LookupError(
LookupError: Missing NLTK data. Run `knowledge init` before using the cluster command.
```

and, after downloading `punk_tab`:

```
cmarcille@ubuntu-laptop:~/Documents/Manuscrit/Manuscrit knowledge cluster -k Knowledge/kl-configure.tex -d main.diagnose
Traceback (most recent call last):
  File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/distance.py", line 124, in breakup_notion
    words_with_POStag = nltk.pos_tag(  # pylint: disable=invalid-name
  File "/home/cm/.local/lib/python3.10/site-packages/nltk/tag/__init__.py", line 168, in pos_tag
    tagger = _get_tagger(lang)
  File "/home/cm/.local/lib/python3.10/site-packages/nltk/tag/__init__.py", line 110, in _get_tagger
    tagger = PerceptronTagger()
  File "/home/cm/.local/lib/python3.10/site-packages/nltk/tag/perceptron.py", line 183, in __init__
    self.load_from_json(lang)
  File "/home/cm/.local/lib/python3.10/site-packages/nltk/tag/perceptron.py", line 273, in load_from_json
    loc = find(f"taggers/averaged_perceptron_tagger_{lang}/")
  File "/home/cm/.local/lib/python3.10/site-packages/nltk/data.py", line 579, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource averaged_perceptron_tagger_eng not found.
  Please use the NLTK Downloader to obtain the resource:

> import nltk
>   >>> nltk.download('averaged_perceptron_tagger_eng')
>   
>   For more information see: https://www.nltk.org/data.html
> 
>   Attempted to load taggers/averaged_perceptron_tagger_eng/
> 
>   Searched in:
>     - '/home/cm/nltk_data'
>     - '/usr/nltk_data'
>     - '/usr/share/nltk_data'
>     - '/usr/lib/nltk_data'
>     - '/usr/share/nltk_data'
>     - '/usr/local/share/nltk_data'
>     - '/usr/lib/nltk_data'
>     - '/usr/local/lib/nltk_data'
> **********************************************************************
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/cm/.local/bin/knowledge", line 8, in <module>
>     sys.exit(cli())
>   File "/home/cm/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/cm/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/home/cm/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/cm/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/cm/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/scripts/app.py", line 130, in cluster
>     clustering.app(kl_filename, dg_filename, scope, print_kl, lang, config_filename)
>   File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/clustering.py", line 38, in app
>     scopes_meaning = scope_meaning.infer_all_scopes(
>   File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/scope_meaning.py", line 68, in infer_all_scopes
>     scopes_meaning[scope], infer_scope(bag, scope, lang, stemmer)
>   File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/scope_meaning.py", line 35, in infer_scope
>     list_kl_broke: list[tuple[list[str], str]] = [
>   File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/scope_meaning.py", line 36, in <listcomp>
>     dist.breakup_notion(kl, lang) for kl in list_kl
>   File "/home/cm/.local/lib/python3.10/site-packages/knowledge_clustering/distance.py", line 133, in breakup_notion
>     raise LookupError(
> LookupError: Missing NLTK data. Run `knowledge init` before using the cluster command.
```

As of v0.7.3, `knowledge init` was running the following commands:
```
nltk.download("punkt")
nltk.download("averaged_perceptron_tagger")
os.system(sys.executable + " -m spacy download en_core_web_sm")
os.system(sys.executable + " -m spacy download fr_core_news_sm")
```
It seems necessary to add
```
nltk.download("punk_tab")
nltk.download('averaged_perceptron_tagger_eng')
```
\+ data for the french perceptron. This occurred with v3.9.1 of `nltk`.

Reported by Clara Marcille.

**Comment by remimorvan** [comment]
Bug also reported by Mikołaj Bojańczyk.
